---
AWSTemplateFormatVersion: 2010-09-09
Description: Create the DatadogAWSIntegration Role

Resources:

  DatadogAWSIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::464622532012:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: f3d969eecc6e401c95f7d8859d69ab83
      RoleName: core-reinforce-dev-datadog-integration

  DatadogAWSIntegrationRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: core-reinforced-dev-datadog-integration
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - autoscaling:Describe*
              - budgets:ViewBudget
              - cloudfront:GetDistributionConfig
              - cloudfront:ListDistributions
              - cloudtrail:DescribeTrails
              - cloudtrail:GetTrailStatus
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - codedeploy:List*
              - codedeploy:BatchGet*
              - directconnect:Describe*
              - dynamodb:List*
              - dynamodb:Describe*
              - ec2:Describe*
              - ecs:Describe*
              - ecs:List*
              - elasticache:Describe*
              - elasticache:List*
              - elasticfilesystem:DescribeFileSystems
              - elasticfilesystem:DescribeTags
              - elasticloadbalancing:Describe*
              - elasticmapreduce:List*
              - elasticmapreduce:Describe*
              - es:ListTags
              - es:ListDomainNames
              - es:DescribeElasticsearchDomains
              - health:DescribeEvents
              - health:DescribeEventDetails
              - health:DescribeAffectedEntities
              - kinesis:List*
              - kinesis:Describe*
              - lambda:AddPermission
              - lambda:GetPolicy
              - lambda:List*
              - lambda:RemovePermission
              - logs:Get*
              - logs:Describe*
              - logs:FilterLogEvents
              - logs:TestMetricFilter
              - logs:PutSubscriptionFilter
              - logs:DeleteSubscriptionFilter
              - logs:DescribeSubscriptionFilters
              - rds:Describe*
              - rds:List*
              - redshift:DescribeClusters
              - redshift:DescribeLoggingStatus
              - route53:List*
              - s3:GetBucketLogging
              - s3:GetBucketLocation
              - s3:GetBucketNotification
              - s3:GetBucketTagging
              - s3:ListAllMyBuckets
              - s3:PutBucketNotification
              - ses:Get*
              - sns:List*
              - sns:Publish
              - sqs:ListQueues
              - support:*
              - tag:GetResources
              - tag:GetTagKeys
              - tag:GetTagValues
            Effect: Allow
            Resource: "*"
      Roles:
        - !Ref DatadogAWSIntegrationRole
