AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles


Mappings:

  AccountMap:
    # cvent-sandbox
    '572724207364':
      AccountName: cvent-sandbox
    # cvent-development
    '504055967630':
      AccountName: cvent-development
    # cvent-integration
    '834623602341':
      AccountName: cvent-integration
    # cvent-production
    '659687181524':
      AccountName: cvent-production
    # cvent-management
    '667621734181':
      AccountName: cvent-management
    # core-app-prod
    '924052762697':
      AccountName: core-app-prod
    # core-cdt-prod
    '611736519059':
      AccountName: core-cdt-prod
    # core-fnd-prod
    '752921502988':
      AccountName: core-fnd-prod
    # eu-ecommerce-prod
    '380741956730':
      AccountName: eu-ecommerce-prod
    # core-reinforce-prod
    '981730702137':
      AccountName: core-reinforce-prod
    # core-reinforce-dev
    '219736445914':
      AccountName: core-reinforce-dev

Resources:

    RoleCoreReinforceDevDevelopmentOracle:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - 
              Effect: Allow
              Principal:
                Service: ec2.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AmazonEC2FullAccess
            - arn:aws:iam::aws:policy/AmazonS3FullAccess
        RoleName: core-reinforce-dev-development-oracle

    InstanceProfileCoreReinforceDevDevelopmentOracle:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Path: /
        Roles:
          - !Ref  RoleCoreReinforceDevDevelopmentOracle
        InstanceProfileName: core-reinforce-dev-development-oracle