---
AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:

  CoreRmqProdNessus:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        RoleName: core-rmq-prod-nessus

  CoreRmqProdNessusProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref CoreRmqProdNessus
      InstanceProfileName: core-rmq-prod-nessus-profile
