# Configurations for CI automation
---

IgnoreAccounts:
    # folder name in repo
    - aws-cc
    - cc-dev

FilesToIgnore:
    - 

IgnoreLintingErrors:
    # Only list accounts that are not already in "IgnoreAccounts"
    - us-ecommerce-prod
