AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles that are custom to the account


# Mappings:

#   AccountMap:
#     # cvent-sandbox
#     '572724207364':
#       AccountName: cvent-sandbox
#     # cvent-development
#     '504055967630':
#       AccountName: cvent-development
#     # cvent-integration
#     '834623602341':
#       AccountName: cvent-integration
#     # cvent-production
#     '659687181524':
#       AccountName: cvent-production
#     # cvent-management
#     '667621734181':
#       AccountName: cvent-management
#     # core-app-prod
#     '924052762697':
#       AccountName: core-app-prod
#     # core-cdt-prod
#     '611736519059':
#       AccountName: core-cdt-prod
#     # core-fnd-prod
#     '752921502988':
#       AccountName: core-fnd-prod
#     # eu-ecommerce-prod
#     '380741956730':
#       AccountName: eu-ecommerce-prod
#     # aws-cc
#     '410104171726':
#       AccountName: aws-cc

Resources:

  RoleAwsCcSyseng:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub
        |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
              },
              "Action": "sts:AssumeRoleWithSAML",
              "Condition": {
                "StringEquals": {
                  "SAML:aud": "https://signin.aws.amazon.com/saml"
                }
              }
            },
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::667621734181:root"
              },
              "Action": "sts:AssumeRole",
              "Condition": {}
            }
          ]
        }
      RoleName: aws-cvt-syseng

  PolicyAwsCcPowerUser:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - 
          Action:
            - iam:AddUserToGroup
            - iam:AttachGroupPolicy
            - iam:AttachRolePolicy
            - iam:AttachUserPolicy
            - iam:CreateAccessKey
            - iam:CreateGroup
            - iam:CreatePolicy
            - iam:CreatePolicyVersion
            - iam:CreateRole
            - iam:CreateSAMLProvider
            - iam:CreateUser
            - iam:CreateVirtualMFADevice
            - iam:DeactivateMFADevice
            - iam:DeleteAccessKey
            - iam:DeleteAccountAlias
            - iam:DeleteAccountPasswordPolicy
            - iam:DeleteGroup
            - iam:DeleteGroupPolicy
            - iam:DeletePolicy
            - iam:DeletePolicyVersion
            - iam:DeleteRole
            - iam:DeleteRolePolicy
            - iam:DeleteSAMLProvider
            - iam:DeleteSSHPublicKey
            - iam:DeleteUser
            - iam:DeleteUserPolicy
            - iam:DeleteVirtualMFADevice
            - iam:DetachGroupPolicy
            - iam:DetachRolePolicy
            - iam:DetachUserPolicy
            - iam:EnableMFADevice
            - iam:PutGroupPolicy
            - iam:PutRolePolicy
            - iam:PutUserPolicy
            - iam:RemoveUserFromGroup
            - iam:UpdateAssumeRolePolicy
            - iam:UpdateGroup
            - iam:UpdateLoginProfile
            - iam:UpdateOpenIDConnectProviderThumbprint
            - iam:UpdateSAMLProvider
            - iam:UpdateSSHPublicKey
            - iam:UpdateServerCertificate
            - iam:UpdateSigningCertificate
            - iam:UpdateUser
            - iam:UploadSSHPublicKey
            - iam:UploadServerCertificate
            - iam:UploadSigningCertificate
          Effect: Deny
          Resource: "*"
        - 
          Effect: Allow
          Action: "*"
          Resource: "*"
      PolicyName: aws-cvt-syseng
      Roles: 
          - !Ref RoleAwsCcSyseng