---
AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:
    RoleCoreConfDevOracle:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: ec2.amazonaws.com
              Action: sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: "CoreConfDevOraclePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "arn:aws:s3:::core-conference-dev-archive/*"
        RoleName: core-conf-dev-conference-oracle   

    InstanceProfileCoreConfDevOracle:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Path: /
        Roles:
          - !Ref  RoleCoreConfDevOracle
        InstanceProfileName: core-conf-dev-conference-oracle
