---
AWSTemplateFormatVersion: 2010-09-09
Description: Create federated IAM roles

Parameters:

  AccountName:
    Description: The name of the AWS account this template is launched in.
    Type: String

Resources:

  Sre:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub
        |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
              },
              "Action": "sts:AssumeRoleWithSAML",
              "Condition": {
                "StringEquals": {
                  "SAML:aud": "https://signin.aws.amazon.com/saml"
                }
              }
            },
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::667621734181:root"
              },
              "Action": "sts:AssumeRole",
              "Condition": {}
            }
          ]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
      RoleName: !Sub
        - "${Account}-sre"
        - Account: !Ref AccountName

  ECSPassthroughPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "iam:GetRole",
                "iam:PassRole"
                
              ],
              "Resource": "arn:aws:iam::684904355706:role/reinvent-ECSServiceRole-us-east-1"
            }
          ]
        }
      PolicyName: cvent-ecs-passthrough
      Roles:
        - !Ref Sre