AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:

  CouchbaseAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:root
            Action: sts:AssumeRole
            Condition: {}
      RoleName: aws-cvt-couchbase-admin

  CouchbaseAssumptionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: aws-cvt-couchbase-admin-assumption
      Roles: 
        - !Ref CouchbaseAdminRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - arn:aws:iam::659687181524:role/aws-cvt-couchbase-admin
              - arn:aws:iam::572724207364:role/aws-cvt-couchbase-admin
              - arn:aws:iam::504055967630:role/aws-cvt-couchbase-admin
              - arn:aws:iam::572724207364:role/aws-cvt-couchbase-admin
              - arn:aws:iam::594924633499:role/aws-cvt-couchbase-admin