---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM roles for deploy-query-service - per account

Parameters:

  AccountName:
    Type: String
    Description: Name of the account this has been deployed on

Resources:

  DeployQueryServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
          - "-"
          - - !Ref AccountName
            - deploy-query-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::504055967630:role/cvent-development-deploy-query-service-task-assume-role
            Action: sts:AssumeRole
            Condition: {}

  DeployQueryServiceEcsReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Join:
          - "-"
          - - !Ref AccountName
            - deploy-query-service-policy
      Roles:
        - !Ref DeployQueryServiceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              - route53:GetHostedZone
              - route53:ListHostedZones
              - route53:ListResourceRecordSets
              - route53:ListHostedZonesByName
