---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create an IAM service user for Social Tables for 3rd party CI integration with ECR

Parameters:
  Name:
    Description: Name of the user to create
    Type: String

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Name
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName:
            Fn::Join:
              - '-'
              - - !Ref Name
                - ecr-create-repo
          PolicyDocument:
            Statement:
              -
                Action:
                  - "ecr:CreateRepository"
                Effect: Allow
                Resource:
                  - "*"
            Version: "2012-10-17"