---
AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:

  AwsCvtDatadevs:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
      RoleName: aws-cvt-datadevs

  AwsCvtDatadevsAssumptionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: aws-cvt-datadevs-assumption
      Roles:
        - !Ref AwsCvtDatadevs
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - arn:aws:iam::668679206736:role/aws-cvt-datadevs
