---
AWSTemplateFormatVersion: 2010-09-09
Description: ICR-2743, Create Kapow Eb Deploy IAM role

Resources:

  CventManagementKpwEbDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      RoleName: cvent-management-kpw-eb-deploy

  CventManagementKpwEbDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cvent-management-kpw-eb-deploy-policy
      Roles:
        - !Ref CventManagementKpwEbDeployRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::449196748993:role/core-kapow-dev-kpw-eb-jenkins-deploy
