---
AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:

  DataEngRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:root
            Action: sts:AssumeRole
            Condition: {}
      RoleName: aws-cvt-dataeng
      ManagedPolicyArns: 
      - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess

  DataEngRoleAssumptionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: aws-cvt-dataeng-assumption
      Roles: 
        - !Ref DataEngRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource: arn:aws:iam::*:role/aws-cvt-dataeng
