AWSTemplateFormatVersion: 2010-09-09
Description: Description
Parameters:
  AccountName:
    Description: Name of the account this template is being deployed too
    Type: String
Resources:
  AwsCvtDevleadsRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRoleWithSAML
          Condition:
            StringEquals:
              SAML:aud: https://signin.aws.amazon.com/saml
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::504055967630:saml-provider/development-okta-sso
        - Action: sts:AssumeRole
          Condition: {}
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::667621734181:root
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
      - arn:aws:iam::504055967630:policy/cvent-transcribe-fullaccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
      - arn:aws:iam::aws:policy/AmazonRedshiftFullAccess
      - arn:aws:iam::aws:policy/AWSAppSyncAdministrator
      - arn:aws:iam::504055967630:policy/cvent-devs-policy
      - arn:aws:iam::aws:policy/AWSSupportAccess
      MaxSessionDuration: 43200
      Path: /
      RoleName: aws-cvt-devleads
    Type: AWS::IAM::Role
