AWSTemplateFormatVersion: 2010-09-09
Description: Description
Parameters:
  AccountName:
    Description: Name of the account this template is being deployed too
    Type: String
Resources:
  AwsCvtDbaManagementDbaSqsAdminPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action: sqs:ListQueues
          Effect: Allow
          Resource: '*'
          Sid: VisualEditor0
        - Action: sqs:*
          Effect: Allow
          Resource:
          - arn:aws:sqs:us-east-1:504055967630:dba_api_inbox
          - arn:aws:sqs:us-east-1:504055967630:dba_api_outbox
          Sid: VisualEditor1
        Version: '2012-10-17'
      PolicyName: cvent-development-dba-sqs-admin
      Roles:
      - Ref: AwsCvtDbaManagementRole
    Type: AWS::IAM::Policy
  AwsCvtDbaManagementRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::667621734181:user/cvent-management-dba-utility
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonRDSFullAccess
      - arn:aws:iam::504055967630:policy/cvent-dba-management-policy
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      MaxSessionDuration: 3600
      Path: /
      RoleName: aws-cvt-dba-management
    Type: AWS::IAM::Role
