---
AWSTemplateFormatVersion: 2010-09-09
Description: Description

Resources:

  AwsCvtDataDevsGlueAndS3Policy:
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - glue:BatchCreatePartition
              - glue:GetCrawler
              - glue:GetTableVersions
              - glue:CreateClassifier
              - glue:GetPartitions
              - glue:UpdateTable
              - glue:UpdateCrawler
              - glue:GetDevEndpoint
              - glue:CreateScript
              - glue:UpdateTrigger
              - glue:GetTrigger
              - glue:GetUserDefinedFunction
              - glue:GetJobRun
              - glue:StopCrawlerSchedule
              - glue:GetUserDefinedFunctions
              - glue:GetClassifier
              - glue:UpdateDatabase
              - glue:GetJobs
              - glue:GetTables
              - glue:CreateTable
              - glue:GetTriggers
              - glue:CreateConnection
              - glue:CreateCrawler
              - glue:GetMapping
              - glue:GetPartition
              - glue:GetDevEndpoints
              - glue:StartCrawlerSchedule
              - glue:StartJobRun
              - glue:UpdateClassifier
              - glue:GetJob
              - glue:GetConnections
              - glue:GetCrawlers
              - glue:GetClassifiers
              - glue:CreateTrigger
              - glue:StopTrigger
              - glue:CreateUserDefinedFunction
              - glue:StopCrawler
              - glue:StartTrigger
              - glue:GetCatalogImportStatus
              - glue:CreateJob
              - glue:ImportCatalogToGlue
              - glue:GetConnection
              - glue:StartCrawler
              - glue:ResetJobBookmark
              - glue:UpdateJob
              - glue:CreatePartition
              - glue:UpdatePartition
              - glue:UpdateUserDefinedFunction
              - glue:BatchGetPartition
              - glue:GetDatabases
              - glue:GetTable
              - glue:GetDatabase
              - glue:GetDataflowGraph
              - glue:UpdateConnection
              - glue:CreateDatabase
              - glue:CreateDevEndpoint
              - glue:UpdateDevEndpoint
              - glue:GetPlan
              - glue:GetCrawlerMetrics
              - glue:GetJobRuns
            Effect: Allow
            Resource: '*'
            Sid: VisualEditor0
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - arn:aws:s3:::cvent-development-datawarehouse/*
              - arn:aws:s3:::arn:aws:s3:::cvent-development-datawarehouse
              - arn:aws:s3:::arn:aws:s3:::cvent-development-cvent-datawarehouse-us-east-1/*
              - arn:aws:s3:::arn:aws:s3:::cvent-development-cvent-datawarehouse-us-east-1
            Sid: VisualEditor1
        Version: '2012-10-17'
      PolicyName: cvent-development-datadev-glue-and-s3-policy
      Roles:
        - !Ref AwsCvtDataDevsRole
    Type: AWS::IAM::Policy

  AwsCvtDataDevsRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
            Effect: Allow
            Principal:
              Federated: arn:aws:iam::504055967630:saml-provider/development-okta-sso
          - Action: sts:AssumeRole
            Condition: {}
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:root
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/AWSSupportAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      MaxSessionDuration: 43200
      Path: /
      RoleName: aws-cvt-datadevs
    Type: AWS::IAM::Role
