---
AWSTemplateFormatVersion: '2010-09-09'
Description: ICR-3328, IAM user to access SocialWall S3 bucket

Parameters:
  UserName:
    Description: Name of the user to create
    Type: String
  PolicyName:
    Description: Name of the inline policy
    Type: String

Resources:
  CventDevelopmentOnsiteSolutionSocialwallUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      Policies:
        - PolicyName: !Ref PolicyName
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload,
                  - s3:GetObjectAcl,
                  - s3:GetObjectVersion,
                  - s3:DeleteObject,
                  - s3:DeleteObjectVersion,
                  - s3:GetObject,
                  - s3:PutObjectAcl,
                  - s3:PutObjectVersionAcl,
                  - s3:PutObject,
                  - s3:GetObjectVersionAcl
                Resource:
                  - arn:aws:s3::517530596106:livestream-stage/*