AWSTemplateFormatVersion: 2010-09-09
Description: Description
Parameters:
  AccountName:
    Description: Name of the account this template is being deployed too
    Type: String
Resources:
  AwsCvtApiPlatformLeadApiPlatformAccessPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - cloudfront:*
          - cognito-identity:*
          - lambda:*
          - cognito-idp:*
          - cognito-sync:*
          Effect: Allow
          Resource: '*'
          Sid: VisualEditor0
        Version: '2012-10-17'
      PolicyName: cvent-development-api-platform-access
      Roles:
      - Ref: AwsCvtApiPlatformLeadRole
    Type: AWS::IAM::Policy
  AwsCvtApiPlatformLeadRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRoleWithSAML
          Condition:
            StringEquals:
              SAML:aud: https://signin.aws.amazon.com/saml
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::504055967630:saml-provider/development-okta-sso
        - Action: sts:AssumeRole
          Condition: {}
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::667621734181:root
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::504055967630:policy/cvent-dms-redshift
      - arn:aws:iam::aws:policy/ReadOnlyAccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonAthenaFullAccess
      - arn:aws:iam::aws:policy/AmazonRedshiftFullAccess
      - arn:aws:iam::504055967630:policy/cvent-devs-policy
      - arn:aws:iam::aws:policy/AWSSupportAccess
      - arn:aws:iam::504055967630:policy/apigateway-stages-admin
      - arn:aws:iam::aws:policy/PowerUserAccess
      MaxSessionDuration: 3600
      Path: /
      RoleName: aws-cvt-api-platform-lead
    Type: AWS::IAM::Role
