AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles


Mappings:

  AccountMap:
    # cvent-sandbox
    '572724207364':
      AccountName: cvent-sandbox
    # cvent-development
    '504055967630':
      AccountName: cvent-development
    # cvent-integration
    '834623602341':
      AccountName: cvent-integration
    # cvent-production
    '659687181524':
      AccountName: cvent-production
    # cvent-management
    '667621734181':
      AccountName: cvent-management
    # core-app-prod
    '924052762697':
      AccountName: core-app-prod
    # core-cdt-prod
    '611736519059':
      AccountName: core-cdt-prod
    # core-fnd-prod
    '752921502988':
      AccountName: core-fnd-prod
    # eu-ecommerce-prod
    '380741956730':
      AccountName: eu-ecommerce-prod

    # core-reinforce-prod
    '981730702137':
      AccountName: core-reinforce-prod

    # core-reinforce-dev
    '219736445914':
      AccountName: core-reinforce-dev

Resources:

  UserCoreReinforceProdSharedJenkins:
    Type: AWS::IAM::User
    Properties: 
      Path: /
      UserName: 
        Fn::Join:
          - "-"
          - - !FindInMap [AccountMap, !Ref "AWS::AccountId", AccountName]
            - shared-jenkins


  RoleCoreReinforceProdSharedJenkins:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Fn::Join:
                - ""
                - - !Sub arn:aws:iam::${AWS::AccountId}:user/
                  - !FindInMap [AccountMap, !Ref "AWS::AccountId", AccountName]
                  - -shared-jenkins
          Action: sts:AssumeRole
      RoleName:
        Fn::Join:
          - "-"
          - - !FindInMap [AccountMap, !Ref "AWS::AccountId", AccountName]
            - shared-jenkins
    DependsOn:
      - UserCoreReinforceProdSharedJenkins

  PolicySharedJenkinsRole:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName:
        Fn::Join:
          - "-"
          - - !FindInMap [AccountMap, !Ref "AWS::AccountId", AccountName]
            - shared-jenkins-policy
      Roles: 
        - !Ref RoleCoreReinforceProdSharedJenkins
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: "*"
            Effect: Allow
            Resource: "*"


  PolicySharedJenkinsUser:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName:
        Fn::Join:
          - "-"
          - - !FindInMap [AccountMap, !Ref "AWS::AccountId", AccountName]
            - shared-jenkins-policy
      Users: 
        - !Ref UserCoreReinforceProdSharedJenkins
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Resource:
              Fn::Join:
                - ""
                - - !Sub arn:aws:iam::${AWS::AccountId}:role/
                  - !FindInMap [AccountMap, !Ref "AWS::AccountId", AccountName]
                  - -shared-jenkins
