AWSTemplateFormatVersion: 2010-09-09
Description: Description
Parameters:
  AccountName:
    Description: Name of the account this template is being deployed too
    Type: String
Resources:
  AwsCvtCouchbaseAdminRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRoleWithSAML
          Condition:
            StringEquals:
              SAML:aud: https://signin.aws.amazon.com/saml
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::572724207364:saml-provider/okta-sso
        - Action: sts:AssumeRole
          Condition: {}
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::667621734181:root
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEC2FullAccess
      MaxSessionDuration: 3600
      Path: /
      RoleName: aws-cvt-couchbase-admin
    Type: AWS::IAM::Role
