AWSTemplateFormatVersion: 2010-09-09
Description: Description

Parameters:
  AccountName:
    Description: Name of the account this template is being deployed too
    Type: String

Resources:
  AWSGlueServiceSageMakerNotebookRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Condition: {}
          Effect: Allow
          Principal:
            Service: sagemaker.amazonaws.com
        Version: '2012-10-17'
      RoleName: AWSGlueServiceSageMakerNotebookRole-Default
    Type: AWS::IAM::Role

    AWSGlueServiceSageMakerNotebookPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: AWSGlueServiceSageMakerNotebook-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
              - s3:ListBucket
            Effect: Allow
            Resource:
            - arn:aws:s3:::cvent-sandbox-datawarehouse-datadev
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Effect: Allow
            Resource:
              - arn:aws:s3:::cvent-sandbox-datawarehouse-datadev*
          - Action:
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
              - logs:CreateLogGroup
            Effect: Allow
            Resource:
              - arn:aws:logs:us-east-1:572724207364:log-group:/aws/sagemaker/*
              - arn:aws:logs:us-east-1:572724207364:log-group:/aws/sagemaker/*:log-stream:aws-glue-*
          - Action:
              - glue:UpdateDevEndpoint
              - glue:GetDevEndpoint
              - glue:GetDevEndpoints
            Effect: Allow
            Resource:
              - arn:aws:glue:us-east-1:572724207364:devEndpoint/datadev-devep-01*
          - Action: comprehend:*
            Effect: Allow
            Resource: "*"
        Roles: AWSGlueServiceSageMakerNotebookRoleAwsCvtDevsRole
