---
AWSTemplateFormatVersion: 2010-09-09
Description: ICR-3461, Create IAM role for DMS vpc

Resources:

  CoreKapowProdDmsVpcRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: sts:AssumeRole
      RoleName: dms-vpc-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole
