---
AWSTemplateFormatVersion: 2010-09-09
Description: Description

Resources:
  AwsCvtDevopsRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
            Effect: Allow
            Principal:
              Federated: arn:aws:iam::853122785612:saml-provider/sso-okta
          - Action: sts:AssumeRole
            Condition: {}
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:root
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::853122785612:policy/cvent-powerusers-policy
      MaxSessionDuration: 3600
      Path: /
      RoleName: aws-cvt-devops
    Type: AWS::IAM::Role
