AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:
    RoleCoreBtDevOracle:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - 
              Effect: Allow
              Principal:
                Service: ec2.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
            - arn:aws:iam::aws:policy/AmazonEC2FullAccess
            - arn:aws:iam::aws:policy/AmazonS3FullAccess
        RoleName: core-bt-dev-oracle

    InstanceProfileCoreBtDevOracle:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Path: /
        Roles:
          - !Ref  RoleCoreBtDevOracle
        InstanceProfileName: core-bt-dev-oracle