---
AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:
    RoleCoreBtDevOracle:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: ec2.amazonaws.com
              Action: sts:AssumeRole
        Path: "/"
        Policies:
        - PolicyName: "CoreBtDevOraclePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "arn:aws:s3:::core-bt-dev-archive/*"
        RoleName: core-bt-dev-business-transient-oracle   

    InstanceProfileCoreBtDevOracle:
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Path: /
        Roles:
          - !Ref  RoleCoreBtDevOracle
        InstanceProfileName: core-bt-dev-business-transient-oracle