---
AWSTemplateFormatVersion: 2010-09-09
Description: Description

Resources:
  AwsCvtAppsupportRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
            Effect: Allow
            Principal:
              Federated: arn:aws:iam::843446578200:saml-provider/emi-development-okta-sso
          - Action: sts:AssumeRole
            Condition: {}
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:root
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      MaxSessionDuration: 3600
      Path: /
      RoleName: aws-cvt-appsupport
    Type: AWS::IAM::Role
