AWSTemplateFormatVersion: 2010-09-09
Description: Description
Parameters:
  AccountName:
    Description: Name of the account this template is being deployed too
    Type: String
Resources:
  AwsCvtNocCventNocPolicyPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - ec2:RebootInstances
          - ec2:StartInstances
          - ec2:StopInstances
          - ec2:ModifyVolume
          - elasticloadbalancing:RegisterTargets",
          - elasticloadbalancing:DeregisterTargets",
          - ecs:ListAttributes
          - ecs:StartTask
          - ecs:DescribeTaskDefinition
          - ecs:DescribeClusters
          - ecs:ListServices
          - ecs:UpdateService
          - ecs:RunTask
          - ecs:ListTasks
          - ecs:ListTaskDefinitionFamilies
          - ecs:StopTask
          - ecs:DescribeServices
          - ecs:ListContainerInstances
          - ecs:DescribeContainerInstances
          - ecs:DescribeTasks
          - ecs:ListTaskDefinitions
          - ecs:ListClusters
          - rds:DescribeDBInstances
          - rds:ModifyDBInstance
          Effect: Allow
          Resource: '*'
          Sid: CventNocPolicy
        Version: '2012-10-17'
      PolicyName: emi-development-cvent-noc-policy
      Roles:
      - Ref: AwsCvtNocRole
    Type: AWS::IAM::Policy
  AwsCvtNocRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRoleWithSAML
          Condition:
            StringEquals:
              SAML:aud: https://signin.aws.amazon.com/saml
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::843446578200:saml-provider/emi-development-okta-sso
        - Action: sts:AssumeRole
          Condition: {}
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::667621734181:root
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
      - arn:aws:iam::aws:policy/AWSSupportAccess
      MaxSessionDuration: 3600
      Path: /
      RoleName: aws-cvt-noc
    Type: AWS::IAM::Role
