AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:


    CoreCdtProdPower:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/PowerUserAccess
            RoleName: core-cdt-prod-power

    CoreCdtProdView:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-view

    CoreCdtProdDevs:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-devs

    CoreCdtProdQa:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-qa

    CoreCdtProdAppSupport:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-appsupport

    CoreCdtProdAppUi:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-ui

    CoreCdtProdSre:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/PowerUserAccess
            RoleName: core-cdt-prod-sre

    CoreCdtAttendeeJourneyDatomicpeer:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/AmazonDynamoDBFullAccess
            RoleName: core-cdt-attendee-journey-datomicpeer

    CoreCdtAttendeeJourneyDatomictransactor:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/AmazonDynamoDBFullAccess
            RoleName: core-cdt-attendee-journey-datomictransactor
