AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:


    CoreCdtProdPower:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/PowerUserAccess
            RoleName: core-cdt-prod-power

    CoreCdtProdView:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-view

    CoreCdtProdDevs:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-devs

    CoreCdtProdQa:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-qa

    CoreCdtProdAppSupport:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-appsupport

    CoreCdtProdAppUi:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
            RoleName: core-cdt-prod-ui

    CoreCdtProdSre:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/PowerUserAccess
            RoleName: core-cdt-prod-sre

    CoreCdtAttendeeJourneyDatomicPeer:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            RoleName: core-cdt-attendee-journey-datomicpeer

    CoreCdtAttendeeJourneyDatomicTransactor:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso"
                      },
                      "Action": "sts:AssumeRoleWithSAML",
                      "Condition": {
                        "StringEquals": {
                          "SAML:aud": "https://signin.aws.amazon.com/saml"
                        }
                      }
                    },
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "AWS": "arn:aws:iam::667621734181:root"
                      },
                      "Action": "sts:AssumeRole",
                      "Condition": {}
                    }
                  ]
                }
            RoleName: core-cdt-attendee-journey-datomictransactor

# Define Custom Policies
    DatomicPeerPolicy1:
        Type: AWS::IAM::Policy
        Properties:
            PolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": [
                          "dynamodb:GetItem",
                          "dynamodb:BatchGetItem",
                          "dynamodb:Scan",
                          "dynamodb:Query"
                      ],
                      "Resource": "arn:aws:dynamodb:*:${AWS::AccountId}:table/core-cdt-prod-attendee-journey-ephemera-P2-production-eu-west-1"
                    }
                  ]
                }
            PolicyName: attendee-journey-ephemera-P2-peer
            Roles:
                -
                    Ref: "CoreCdtAttendeeJourneyDatomicPeer"

    DatomicPeerPolicy2:
        Type: AWS::IAM::Policy
        Properties:
            PolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Action": [
                          "dynamodb:GetItem",
                          "dynamodb:BatchGetItem",
                          "dynamodb:Scan",
                          "dynamodb:Query"
                      ],
                      "Resource": "arn:aws:dynamodb:*:${AWS::AccountId}:table/core-cdt-prod-attendee-journey-kenoma-P2-production-eu-west-1"
                    }
                  ]
                }
            PolicyName: attendee-journey-kenoma-P2-peer
            Roles:
                -
                    Ref: "CoreCdtAttendeeJourneyDatomicPeer"

    DatomicTransactorPolicy1:
        Type: AWS::IAM::Policy
        Properties:
            PolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                      {
                          "Effect": "Allow",
                          "Action": [
                              "dynamodb:*"
                          ],
                          "Resource": [
                              "arn:aws:dynamodb:*:${AWS::AccountId}:table/core-cdt-prod-attendee-journey-ephemera-P2-production-eu-west-1",
                              "arn:aws:dynamodb:*:${AWS::AccountId}:table/core-cdt-prod-attendee-journey-kenoma-P2-production-eu-west-1"
                          ]
                      },
                      {
                          "Effect": "Allow",
                          "Action": [
                              "cloudwatch:PutMetricData",
                              "cloudwatch:PutMetricDataBatch"
                          ],
                          "Resource": "*",
                          "Condition": {
                              "Bool": {
                                  "aws:SecureTransport": "true"
                              }
                          }
                      }
                  ]
                }
            PolicyName: cvent-policy-attendee-journey-datomic
            Roles:
                -
                    Ref: "CoreCdtAttendeeJourneyDatomicTransactor"

    DatomicTransactorPolicy2:
        Type: AWS::IAM::Policy
        Properties:
            PolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                      {
                          "Effect": "Allow",
                          "Action": [
                              "dynamodb:*"
                          ],
                          "Resource": "arn:aws:dynamodb:*:${AWS::AccountId}:table/core-cdt-prod-attendee-journey-ephemera-P2-production-eu-west-1"
                      }
                  ]
                }
            PolicyName: attendee-journey-ephemera-P2-transactor
            Roles:
                -
                    Ref: "CoreCdtAttendeeJourneyDatomicTransactor"

    DatomicTransactorPolicy3:
        Type: AWS::IAM::Policy
        Properties:
            PolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                      {
                          "Effect": "Allow",
                          "Action": [
                              "dynamodb:*"
                          ],
                          "Resource": "arn:aws:dynamodb:*:${AWS::AccountId}:table/core-cdt-prod-attendee-journey-kenoma-P2-production-eu-west-1"
                      }
                  ]
                }
            PolicyName: attendee-journey-kenoma-P2-transactor
            Roles:
                -
                    Ref: "CoreCdtAttendeeJourneyDatomicTransactor"

    DatomicTransactorPolicy4:
        Type: AWS::IAM::Policy
        Properties:
            PolicyDocument: !Sub
                |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                      {
                          "Effect": "Allow",
                          "Action": [
                              "cloudwatch:PutMetricData",
                              "cloudwatch:PutMetricDataBatch"
                          ],
                          "Resource": "*",
                          "Condition": {
                              "Bool": {
                                  "aws:SecureTransport": "true"
                              }
                          }
                      }
                  ]
                }
            PolicyName: transactor-metrics
            Roles:
                -
                    Ref: "CoreCdtAttendeeJourneyDatomicTransactor"
