---
AWSTemplateFormatVersion: 2010-09-09
Description: Creates role for security hub automatic deployment

Parameters:

  AccountName:
    Type: String
    Description: Name of the account this has been deployed on

Resources:

  SecurityHubEc2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      RoleName:
        Fn::Join:
          - "-"
          - - !Ref AccountName
            - security-hub-ec2

  SecurityHubEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SecurityHubEc2Role
      InstanceProfileName:
        Fn::Join:
          - "-"
          - - !Ref AccountName
            - security-hub-ec2

  SecurityHubPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Join:
          - "-"
          - - !Ref AccountName
            - assumption
      Roles:
        - !Ref SecurityHubEc2Role
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Resource:
              - arn:aws:iam::*:role/security-hub-poc
            Effect: Allow
