AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM Role and MasterPolicy list for MISP

Resources:
  RoleCoreSecProdMisp:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              SERVICE: 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      RoleName: core-sec-prod-security-misp

  PolicyCoreSecProdMisp:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'core-sec-prod-security-misp'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: MISP
            Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:PutObject
              - lambda:InvokeFuntion
              - rds-db:connect
            Effect: 'Allow'
            Resource: '*'
      Roles:
        - Ref: 'MispRole'

  InstanceProfileCoreSecProdMisp:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref RoleCoreSecProdMisp
      InstanceProfileName: core-sec-prod-security-misp
