AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles

Resources:

  CoreSecProdNessus:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  -
                    Effect: Allow
                    Principal:
                      Service: ec2.amazonaws.com
                    Action: sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/job-function/AmazonEC2ReadOnlyAccess
            RoleName: core-sec-prod-nessus
