---
AWSTemplateFormatVersion: 2010-09-09
Description: Datadog and AWS integration IAM role

Parameters:
    ExternalId:
        Description: The external ID of the Datadog integration
        Type: String

    RoleName:
        Description: The name of the IAM role
        Type: String

Resources:

    DatadogRole:
        Type: AWS::IAM::Role
        Properties:
            RoleName: DatadogAWSIntegrationRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/AWSHealthFullAccess
                - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
                - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
            AssumeRolePolicyDocument: !Sub
                |
                {
                    "Version": "2012-10-17",
                    "Statement": [{
                        "Effect": "Allow",
                        "Principal": {
                            "AWS": "arn:aws:iam::464622532012:root"
                        },
                        "Action": "sts:AssumeRole",
                        "Condition": {
                            "StringEquals": {
                                "sts:ExternalId": "${ExternalId}"
                            }
                        }
                    }]
                }

    DatadogPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: datadog-aws-integration-policy
            Roles:
                - !Ref "DatadogRole"
            PolicyDocument:
                |
                {
                  "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Action": [
                                "autoscaling:Describe*",
                                "budgets:ViewBudget",
                                "cloudtrail:DescribeTrails",
                                "cloudtrail:GetTrailStatus",
                                "cloudwatch:Describe*",
                                "cloudwatch:Get*",
                                "cloudwatch:List*",
                                "codedeploy:BatchGet*",
                                "codedeploy:List*",
                                "dynamodb:describe*",
                                "dynamodb:list*",
                                "ec2:Describe*",
                                "ec2:Get*",
                                "ecs:Describe*",
                                "ecs:List*",
                                "elasticache:Describe*",
                                "elasticache:List*",
                                "elasticfilesystem:DescribeFileSystems",
                                "elasticfilesystem:DescribeTags",
                                "elasticloadbalancing:Describe*",
                                "elasticmapreduce:Describe*",
                                "elasticmapreduce:List*",
                                "es:DescribeElasticsearchDomains",
                                "es:ListDomainNames",
                                "es:ListTags",
                                "kinesis:Describe*",
                                "kinesis:List*",
                                "lambda:List*",
                                "logs:Describe*",
                                "logs:FilterLogEvents",
                                "logs:Get*",
                                "logs:TestMetricFilter",
                                "rds:Describe*",
                                "rds:List*",
                                "route53:List*",
                                "s3:GetBucketTagging",
                                "s3:ListAllMyBuckets",
                                "ses:Get*",
                                "sns:List*",
                                "sns:Publish",
                                "sqs:ListQueues",
                                "tag:GetResources",
                                "tag:getTagKeys",
                                "tag:getTagValues"
                            ],
                            "Effect": "Allow",
                            "Resource": "*"
                        }
                    ]
                }
