---
AWSTemplateFormatVersion: 2010-09-09
Description: Create base IAM roles
Resources:

  RoleCorpEntsrvProdDba:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/okta-sso
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
                SAML:aud: https://signin.aws.amazon.com/saml
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:root
            Action: sts:AssumeRole
            Condition: {}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      RoleName: corp-entsrv-prod-dba

  PolicyCorpEntsrvProdDba:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: corp-entsrv-prod-dba
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Action:
            - rds:ModifyDBInstance
            - es:DescribeReservedElasticsearchInstances
          Effect: Allow
          Resource: "*"
      Roles:
        - Ref: RoleCorpEntsrvProdDba
