---
AWSTemplateFormatVersion: 2010-09-09
Description: ICR-2743, Create IAM role for Kapow EB jenkins deployments

Resources:

  KpwEbJenkinsDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:role/cvent-management-kpw-eb-deploy
            Action: sts:AssumeRole
      RoleName: core-kapow-dev-kpw-eb-jenkins-deploy

  KpwEbJenkinsDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: core-kapow-dev-kpw-eb-jenkins-deploy-policy
      Roles:
        - !Ref KpwEbJenkinsDeployRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - s3:Get*
              - s3:List*
              - s3:PutObject
            Resource:
              - "arn:aws:s3:::core-kapow-dev-kpw-eb-us-east-1/*"
              - "arn:aws:s3:::core-kapow-dev-kpw-eb-us-east-1"
          - Effect: "Allow"
            Action:
              - ec2:Describe*
              - elasticloadbalancing:Describe*
              - elasticbeanstalk:Check*
              - elasticbeanstalk:Describe*
              - elasticbeanstalk:List*
              - elasticbeanstalk:CreateApplicationVersion
              - elasticbeanstalk:UpdateApplicationVersion
              - elasticbeanstalk:UpdateEnvironment
              - elasticbeanstalk:RequestEnvironmentInfo
              - elasticbeanstalk:RetrieveEnvironmentInfo
            Resource: "*"
