AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  OriginS3Bucket:
    Description: S3 bucket that will source your images.
    Type: String
    ConstraintDescription: Must be a valid S3 Bucket.
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9-.]*'
  UIDestPrefix:
    Description: Prefix for UI files in S3 bucket (currently only supports one folder)
    Type: String
    Default: serverless-image-handler-ui/
    ConstraintDescription: Prefix must contains letters, numbers, or dashes and end
      with a forward slash (/); it cannot start with a forward slash or contain a
      forward slash -- for example 'serverless-image-handler-ui/'
    AllowedPattern: ^(?!/)[a-zA-Z][a-zA-Z0-9-]+/$
  UISrcBucket:
    Description: UI Source Bucket
    Type: String
    ConstraintDescription: Must be a valid S3 Bucket.
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9-.]*'
    Default: xb-assets-dev
  UISrcKey:
    Description: UI Source Key
    Type: String
    Default: serverless-image-handler/latest/serverless-image-handler-ui.zip
Resources:
  CustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
  CustomResourceLoggingPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref 'CustomResourceRole'
      PolicyName: Image_Handler_Custom_Resource_Logging_Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Join
              - ''
              - - 'arn:aws:logs:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - :log-group:/aws/lambda/*
  CustomResourceDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref 'CustomResourceRole'
      PolicyName: Image_Handler_Custom_Resource_S3_Deploy_Policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'UISrcBucket'
                - '-'
                - !Ref 'AWS::Region'
                - /
                - !Ref 'UISrcKey'
          - Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:PutObject
              - s3:PutObjectAcl
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'OriginS3Bucket'
                - /
                - !Ref 'UIDestPrefix'
                - '*'
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref 'OriginS3Bucket'
