---
AWSTemplateFormatVersion: 2010-09-09
Description: Create IAM role for Kapow EB jenkins deployments

Resources:

  KpwEbJenkinsDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::667621734181:role/cvent-management-kpw-eb-deploy
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: KpwEbJenkinsDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:PutObject
                Resource:
                  - "arn:aws:s3:::core-kapow-dev-kpw-eb-us-east-1/*"
                  - "arn:aws:s3:::core-kapow-dev-kpw-eb-us-east-1"
              -
                Effect: "Allow"
                Action:
                  - ec2:Describe*
                  - elasticbeanstalk:Describe*
                  - elasticbeanstalk:CreateApplicationVersion
                  - elasticbeanstalk:UpdateApplicationVersion
                  - elasticbeanstalk:UpdateEnvironment
                Resource: "*"
      RoleName: kpw-eb-jenkins-deploy
